server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      location: files
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: mind-assess
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.amosdzhn.space:10000/db_dxsxl?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    name: defaultDataSource
    username: auser
    password: GOGO123..
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  redis:
    host: www.amosdzhn.space
    port: 6379
    database: 0
    password: 123456!
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 20
        min-idle: 0
    timeout: 8000
mybatis-plus:
  type-aliases-package: com.cqjtu.mindassess.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
minio:
  end-point: http://www.amosdzhn.space:9000
  access-key: 7ED2W1KFS4EF718Y2YVH
  secret-key: UJ8X+g5YYrunataKDqpQnn9MnT+njmR0CfnpqPXR
  bucket: mentalhealth
  access-url-prefix: http://www.amosdzhn.space:9000
knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: a
    password: a
short-message:
  tencent-sm:
    endpoint: sms.tencentcloudapi.com
    region: ap-guangzhou
    secret-id: AKIDiFVUDfqjLgkX3JI0RcW8TXKq52i8G8k5
    secret-key: 5tRggQt62i8H9k47uQfeNp0uYv1pMddM
    sdk-appid: 1400644446
    sign: 张宁个人笔记网
    template-ids:
      - 1355525  # 注册短信模板id
      - 1355526  # 登录短信模板id
      - 1391199  # 通用模板id
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Access-Token
  # token有效期，单位s 默认30天, -1代表永不过期 604,800 2592000
  timeout: 604800  # 一周
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
# ASRT Client 配置
asrt:
  host: www.amosdzhn.space
  port: 20001
  protocol: http
# aliyun 智能语音服务
aliyun-intelligent-voice:
  accessKeyId: LTAI5t6sTJU6rUmycweMbZsn
  accessKeySecret: OdSAHhTmYFTlayPXQ016uMnMLqo1z6
  appKey: 1bSEFiS4JoJx0COt