server:
  port: 8080
spring:
  application:
    name: mind-assess
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.amosdzhn.space:10000/db_dxsxl?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    name: defaultDataSource
    username: auser
    password: GOGO123..
    hikari:
      max-lifetime: 60000
  redis:
    host: www.amosdzhn.space
    port: 6379
    database: 0
    password: 123456!
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
#shiro:
#  web:
#    enabled: true
#  successUrl: /index
#  loginUrl: /user/login
#  sessionManager:
#    sessionIdCookieEnabled: true
#  unauthorizedUrl: /login
mybatis-plus:
  type-aliases-package: com.cqjtu.mindassess.entity
  mapper-locations: classpath:/mapper/*mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
minio:
  end-point: http://www.amosdzhn.space:9000
  access-key: 7ED2W1KFS4EF718Y2YVH
  secret-key: UJ8X+g5YYrunataKDqpQnn9MnT+njmR0CfnpqPXR
  bucket: mentalhealth
  access-url-prefix: http://www.amosdzhn.space:9000
knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: a
    password: a
short-message:
  tencent-sm:
    endpoint: sms.tencentcloudapi.com
    region: ap-guangzhou
    secret-id: AKIDiFVUDfqjLgkX3JI0RcW8TXKq52i8G8k5
    secret-key: 5tRggQt62i8H9k47uQfeNp0uYv1pMddM
    sdk-appid: 1400644446
    sign: 张宁个人笔记网
    template-ids:
      - 1355525  # 注册